#ifndef ARM64_DECODE_H
#define ARM64_DECODE_H

/*
输入是一条 32 位指令 word，输出是与运行环境无关的结构化语义；
*/

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <stdint.h>
#endif

#define ARM64_SYSREG_KEY(OP0, OP1, CRN, CRM, OP2) ((((OP0) & 0x3) << 14) | (((OP1) & 0x7) << 11) | (((CRN) & 0xF) << 7) | (((CRM) & 0xF) << 3) | ((OP2) & 0x7))

enum
{
    ARM64_SIMD_ROTATION_0,
    ARM64_SIMD_ROTATION_90,
    ARM64_SIMD_ROTATION_180,
    ARM64_SIMD_ROTATION_270,
};

enum arm64_decode_status
{
    ARM64_DECODE_OK,            // 指令已完整解码，instruction 和对应 operands 有效。
    ARM64_DECODE_UNSUPPORTED,   // 已识别指令大类，但当前还没有提供完整语义。
    ARM64_DECODE_UNPREDICTABLE, // 编码已分配，但其行为受架构 constrained-unpredictable 约束。
    ARM64_DECODE_UNALLOCATED,   // 这个机器码不是架构分配的合法指令
};

// 具体指令及其编码形式；按每项可成功解码的最低完整机器码升序排列。
// 分隔注释中的 0xXX...... 表示该连续分组的起始机器码高字节，括号内只列代表指令。
// 为保持机器码顺序，同一顶层指令大类可能分布在多个连续区间。
enum arm64_instruction
{
    // 未知指令。
    ARM64_INSN_UNKNOWN,

    // 0x08...... 加载与存储：独占、CAS 与有序原子（STXR、LDXR、CAS）。
    ARM64_INSN_STXR,
    ARM64_INSN_STLXR,
    ARM64_INSN_CASP,
    ARM64_INSN_CASPL,
    ARM64_INSN_LDXR,
    ARM64_INSN_LDAXR,
    ARM64_INSN_CASPA,
    ARM64_INSN_CASPAL,
    ARM64_INSN_STLLR,
    ARM64_INSN_STLR,
    ARM64_INSN_CAS,
    ARM64_INSN_CASL,
    ARM64_INSN_LDLAR,
    ARM64_INSN_LDAR,
    ARM64_INSN_CASA,
    ARM64_INSN_CASAL,

    // 0x0A...... 寄存器数据处理：逻辑及加法（AND、BIC、ADD）。
    ARM64_INSN_AND_SHIFTED_REGISTER,
    ARM64_INSN_BIC_SHIFTED_REGISTER,
    ARM64_INSN_ADD_SHIFTED_REGISTER,
    ARM64_INSN_ADD_EXTENDED_REGISTER,

    // 0x0E...... SIMD 与浮点数据处理：向量重排、算术与逐元素运算（UZP1、FMLA、SDOT）。
    ARM64_INSN_UZP1_VECTOR,
    ARM64_INSN_TRN1_VECTOR,
    ARM64_INSN_ZIP1_VECTOR,
    ARM64_INSN_UZP2_VECTOR,
    ARM64_INSN_TRN2_VECTOR,
    ARM64_INSN_ZIP2_VECTOR,
    ARM64_INSN_DUP_ELEMENT_VECTOR,
    ARM64_INSN_DUP_GENERAL_VECTOR,
    ARM64_INSN_SMOV_VECTOR_TO_GPR,
    ARM64_INSN_UMOV_VECTOR_TO_GPR,
    ARM64_INSN_SHADD_VECTOR,
    ARM64_INSN_REV64_VECTOR,
    ARM64_INSN_SQADD_VECTOR,
    ARM64_INSN_SRHADD_VECTOR,
    ARM64_INSN_REV16_VECTOR,
    ARM64_INSN_AND_VECTOR,
    ARM64_INSN_SHSUB_VECTOR,
    ARM64_INSN_SQSUB_VECTOR,
    ARM64_INSN_CMGT_VECTOR,
    ARM64_INSN_CMGE_VECTOR,
    ARM64_INSN_SSHL_VECTOR,
    ARM64_INSN_SQSHL_VECTOR,
    ARM64_INSN_SRSHL_VECTOR,
    ARM64_INSN_SQRSHL_VECTOR,
    ARM64_INSN_SMAX_VECTOR,
    ARM64_INSN_SMIN_VECTOR,
    ARM64_INSN_SABD_VECTOR,
    ARM64_INSN_SABA_VECTOR,
    ARM64_INSN_ADD_VECTOR,
    ARM64_INSN_CMTST_VECTOR,
    ARM64_INSN_MLA_VECTOR,
    ARM64_INSN_MUL_VECTOR,
    ARM64_INSN_SMAXP_VECTOR,
    ARM64_INSN_SMINP_VECTOR,
    ARM64_INSN_ADDP_VECTOR,
    ARM64_INSN_FMAXNM_VECTOR,
    ARM64_INSN_FMLA_VECTOR,
    ARM64_INSN_FADD_VECTOR,
    ARM64_INSN_FMULX_VECTOR,
    ARM64_INSN_FCMEQ_VECTOR,
    ARM64_INSN_FMLAL_VECTOR,
    ARM64_INSN_FMAX_VECTOR,
    ARM64_INSN_FRECPS_VECTOR,
    ARM64_INSN_XTN_VECTOR,
    ARM64_INSN_SQXTN_VECTOR,
    ARM64_INSN_FCVTNS_SIMD_VECTOR,
    ARM64_INSN_FCVTMS_SIMD_VECTOR,
    ARM64_INSN_FCVTAS_SIMD_VECTOR,
    ARM64_INSN_SCVTF_SIMD_VECTOR,
    ARM64_INSN_SADDLV_VECTOR,
    ARM64_INSN_SMAXV_VECTOR,
    ARM64_INSN_FMAXNMV_SCALAR_REDUCE,
    ARM64_INSN_FMAXV_SCALAR_REDUCE,
    ARM64_INSN_SMINV_VECTOR,
    ARM64_INSN_ADDV_VECTOR,
    ARM64_INSN_BIC_VECTOR,
    ARM64_INSN_SQDMULH_VECTOR,
    ARM64_INSN_SDOT_VECTOR,
    ARM64_INSN_USDOT_VECTOR,
    ARM64_INSN_ORR_VECTOR,
    ARM64_INSN_FMINNM_VECTOR,
    ARM64_INSN_FCMGT_ZERO_VECTOR,
    ARM64_INSN_FMLS_VECTOR,
    ARM64_INSN_FSUB_VECTOR,
    ARM64_INSN_FCMEQ_ZERO_VECTOR,
    ARM64_INSN_FAMAX_VECTOR,
    ARM64_INSN_FCMLT_ZERO_VECTOR,
    ARM64_INSN_FMLSL_VECTOR,
    ARM64_INSN_FMIN_VECTOR,
    ARM64_INSN_FABS_VECTOR,
    ARM64_INSN_FRSQRTS_VECTOR,
    ARM64_INSN_FCVTPS_SIMD_VECTOR,
    ARM64_INSN_FCVTZS_SIMD_VECTOR,
    ARM64_INSN_FMINNMV_SCALAR_REDUCE,
    ARM64_INSN_FMINV_SCALAR_REDUCE,
    ARM64_INSN_ORN_VECTOR,
    ARM64_INSN_MOVI_VECTOR_IMMEDIATE,
    ARM64_INSN_FMLA_VECTOR_BY_ELEMENT,
    ARM64_INSN_ORR_VECTOR_IMMEDIATE,
    ARM64_INSN_FMLS_VECTOR_BY_ELEMENT,
    ARM64_INSN_FMUL_VECTOR_BY_ELEMENT,
    ARM64_INSN_SUDOT_VECTOR_BY_ELEMENT,
    ARM64_INSN_FMOV_VECTOR_IMMEDIATE,
    ARM64_INSN_SSHR_VECTOR_IMMEDIATE,
    ARM64_INSN_SHL_VECTOR_IMMEDIATE,
    ARM64_INSN_BFDOT_VECTOR_BY_ELEMENT,
    ARM64_INSN_FMLAL_VECTOR_BY_ELEMENT,
    ARM64_INSN_FMLSL_VECTOR_BY_ELEMENT,
    ARM64_INSN_SDOT_VECTOR_BY_ELEMENT,
    ARM64_INSN_USDOT_VECTOR_BY_ELEMENT,
    ARM64_INSN_BFMLALB_VECTOR_BY_ELEMENT,

    // 0x10...... 立即数数据处理：PC 相对、算术/逻辑与位域（ADR、ADD、SBFM）。
    ARM64_INSN_ADR,
    ARM64_INSN_ADD_IMMEDIATE,
    ARM64_INSN_SMAX_IMMEDIATE,
    ARM64_INSN_UMAX_IMMEDIATE,
    ARM64_INSN_SMIN_IMMEDIATE,
    ARM64_INSN_UMIN_IMMEDIATE,
    ARM64_INSN_AND_IMMEDIATE,
    ARM64_INSN_MOVN,
    ARM64_INSN_SBFM,
    ARM64_INSN_EXTR,

    // 0x14...... 分支、异常与系统：无条件立即分支（B）。
    ARM64_INSN_B,

    // 0x18...... 加载与存储：GPR 字面量及 RCpc 非对齐访存（LDR literal、STLUR、LDAPUR）。
    ARM64_INSN_LDR_LITERAL_GPR,
    ARM64_INSN_STLUR,
    ARM64_INSN_LDAPUR,
    ARM64_INSN_LDAPUR_SIGNED,

    // 0x1A...... 寄存器数据处理：带进位、条件选择与乘除（ADC、CSEL、MADD）。
    ARM64_INSN_ADC,
    ARM64_INSN_CSEL,
    ARM64_INSN_CSINC,
    ARM64_INSN_UDIV,
    ARM64_INSN_SDIV,
    ARM64_INSN_LSLV,
    ARM64_INSN_LSRV,
    ARM64_INSN_ASRV,
    ARM64_INSN_RORV,
    ARM64_INSN_CRC32B,
    ARM64_INSN_CRC32H,
    ARM64_INSN_CRC32W,
    ARM64_INSN_CRC32CB,
    ARM64_INSN_CRC32CH,
    ARM64_INSN_CRC32CW,
    ARM64_INSN_SMAX_REGISTER,
    ARM64_INSN_UMAX_REGISTER,
    ARM64_INSN_SMIN_REGISTER,
    ARM64_INSN_UMIN_REGISTER,
    ARM64_INSN_MADD,
    ARM64_INSN_MSUB,

    // 0x1C...... 加载与存储：FP/SIMD 字面量加载（LDR S、LDR D、LDR Q）。
    ARM64_INSN_LDR_LITERAL_FP_SIMD,

    // 0x1E...... SIMD 与浮点数据处理：标量浮点转换、比较与算术（FCVTNS、FMUL、FMADD）。
    ARM64_INSN_FCVTNS_GPR,
    ARM64_INSN_FCCMP_SCALAR,
    ARM64_INSN_FCCMPE_SCALAR,
    ARM64_INSN_FMUL_SCALAR,
    ARM64_INSN_FCSEL_SCALAR,
    ARM64_INSN_FMOV_SCALAR_IMMEDIATE,
    ARM64_INSN_FDIV_SCALAR,
    ARM64_INSN_FCMP_REGISTER_SCALAR,
    ARM64_INSN_FCMP_ZERO_SCALAR,
    ARM64_INSN_FCMPE_REGISTER_SCALAR,
    ARM64_INSN_FCMPE_ZERO_SCALAR,
    ARM64_INSN_FADD_SCALAR,
    ARM64_INSN_FSUB_SCALAR,
    ARM64_INSN_FMOV_SCALAR,
    ARM64_INSN_FMAX_SCALAR,
    ARM64_INSN_FMIN_SCALAR,
    ARM64_INSN_FMAXNM_SCALAR,
    ARM64_INSN_FMINNM_SCALAR,
    ARM64_INSN_FNMUL_SCALAR,
    ARM64_INSN_FABS_SCALAR,
    ARM64_INSN_FCVTNU_GPR,
    ARM64_INSN_FNEG_SCALAR,
    ARM64_INSN_FSQRT_SCALAR,
    ARM64_INSN_SCVTF_S_W,
    ARM64_INSN_FCVT_D_S,
    ARM64_INSN_UCVTF_S_W,
    ARM64_INSN_FCVTAS_GPR,
    ARM64_INSN_FRINTN_SCALAR,
    ARM64_INSN_FRINTP_SCALAR,
    ARM64_INSN_FCVTAU_GPR,
    ARM64_INSN_FRINTM_SCALAR,
    ARM64_INSN_FRINTZ_SCALAR,
    ARM64_INSN_FMOV_FP_TO_GPR,
    ARM64_INSN_FRINTA_SCALAR,
    ARM64_INSN_FMOV_GPR_TO_FP,
    ARM64_INSN_FRINTX_SCALAR,
    ARM64_INSN_FRINTI_SCALAR,
    ARM64_INSN_FCVTPS_GPR,
    ARM64_INSN_FCVTPU_GPR,
    ARM64_INSN_FCVTMS_GPR,
    ARM64_INSN_FCVTMU_GPR,
    ARM64_INSN_FCVTZS_GPR,
    ARM64_INSN_FCVTZU_GPR,
    ARM64_INSN_SCVTF_D_W,
    ARM64_INSN_FCVT_S_D,
    ARM64_INSN_UCVTF_D_W,
    ARM64_INSN_FMADD_SCALAR,
    ARM64_INSN_FMSUB_SCALAR,
    ARM64_INSN_FNMADD_SCALAR,
    ARM64_INSN_FNMSUB_SCALAR,

    // 0x28...... 加载与存储：GPR 成对访存（STNP、LDP、STP）。
    ARM64_INSN_STNP_GPR,
    ARM64_INSN_LDNP_GPR,
    ARM64_INSN_STP_GPR_POST_INDEX,
    ARM64_INSN_LDP_GPR_POST_INDEX,
    ARM64_INSN_STP_GPR_OFFSET,
    ARM64_INSN_LDP_GPR_OFFSET,
    ARM64_INSN_STP_GPR_PRE_INDEX,
    ARM64_INSN_LDP_GPR_PRE_INDEX,

    // 0x2A...... 寄存器数据处理：逻辑或与置标志加法（ORR、ORN、ADDS）。
    ARM64_INSN_ORR_SHIFTED_REGISTER,
    ARM64_INSN_ORN_SHIFTED_REGISTER,
    ARM64_INSN_ADDS_SHIFTED_REGISTER,
    ARM64_INSN_ADDS_EXTENDED_REGISTER,

    // 0x2C...... 加载与存储：FP/SIMD 成对访存（STNP、LDP、STP）。
    ARM64_INSN_STNP_FP_SIMD,
    ARM64_INSN_LDNP_FP_SIMD,
    ARM64_INSN_STP_FP_SIMD_POST_INDEX,
    ARM64_INSN_LDP_FP_SIMD_POST_INDEX,
    ARM64_INSN_STP_FP_SIMD_OFFSET,
    ARM64_INSN_LDP_FP_SIMD_OFFSET,
    ARM64_INSN_STP_FP_SIMD_PRE_INDEX,
    ARM64_INSN_LDP_FP_SIMD_PRE_INDEX,

    // 0x2E...... SIMD 与浮点数据处理：向量提取、无符号算术与点积（EXT、UQADD、UDOT）。
    ARM64_INSN_EXT_VECTOR,
    ARM64_INSN_UHADD_VECTOR,
    ARM64_INSN_REV32_VECTOR,
    ARM64_INSN_UQADD_VECTOR,
    ARM64_INSN_URHADD_VECTOR,
    ARM64_INSN_EOR_VECTOR,
    ARM64_INSN_UHSUB_VECTOR,
    ARM64_INSN_UQSUB_VECTOR,
    ARM64_INSN_CMHI_VECTOR,
    ARM64_INSN_CMHS_VECTOR,
    ARM64_INSN_USHL_VECTOR,
    ARM64_INSN_UQSHL_VECTOR,
    ARM64_INSN_URSHL_VECTOR,
    ARM64_INSN_UQRSHL_VECTOR,
    ARM64_INSN_UMAX_VECTOR,
    ARM64_INSN_UMIN_VECTOR,
    ARM64_INSN_UABD_VECTOR,
    ARM64_INSN_UABA_VECTOR,
    ARM64_INSN_SUB_VECTOR,
    ARM64_INSN_CMEQ_VECTOR,
    ARM64_INSN_MLS_VECTOR,
    ARM64_INSN_PMUL_VECTOR,
    ARM64_INSN_UMAXP_VECTOR,
    ARM64_INSN_UMINP_VECTOR,
    ARM64_INSN_FMAXNMP_VECTOR,
    ARM64_INSN_FMLAL2_VECTOR,
    ARM64_INSN_FADDP_VECTOR,
    ARM64_INSN_FMUL_VECTOR,
    ARM64_INSN_FCMGE_VECTOR,
    ARM64_INSN_FACGE_VECTOR,
    ARM64_INSN_FMAXP_VECTOR,
    ARM64_INSN_FDIV_VECTOR,
    ARM64_INSN_SQXTUN_VECTOR,
    ARM64_INSN_UQXTN_VECTOR,
    ARM64_INSN_FCVTNU_SIMD_VECTOR,
    ARM64_INSN_FCVTMU_SIMD_VECTOR,
    ARM64_INSN_FCVTAU_SIMD_VECTOR,
    ARM64_INSN_UCVTF_SIMD_VECTOR,
    ARM64_INSN_UADDLV_VECTOR,
    ARM64_INSN_UMAXV_VECTOR,
    ARM64_INSN_UMINV_VECTOR,
    ARM64_INSN_SQRDMLAH_VECTOR,
    ARM64_INSN_SQRDMLSH_VECTOR,
    ARM64_INSN_FCMLA_VECTOR,
    ARM64_INSN_FCADD_VECTOR,
    ARM64_INSN_BFDOT_VECTOR,
    ARM64_INSN_BSL_VECTOR,
    ARM64_INSN_SQRDMULH_VECTOR,
    ARM64_INSN_UDOT_VECTOR,
    ARM64_INSN_BIT_VECTOR,
    ARM64_INSN_FMINNMP_VECTOR,
    ARM64_INSN_FCMGE_ZERO_VECTOR,
    ARM64_INSN_FMLSL2_VECTOR,
    ARM64_INSN_FABD_VECTOR,
    ARM64_INSN_FCMLE_ZERO_VECTOR,
    ARM64_INSN_FAMIN_VECTOR,
    ARM64_INSN_FCMGT_VECTOR,
    ARM64_INSN_FACGT_VECTOR,
    ARM64_INSN_FMINP_VECTOR,
    ARM64_INSN_FNEG_VECTOR,
    ARM64_INSN_FSCALE_VECTOR,
    ARM64_INSN_FCVTPU_SIMD_VECTOR,
    ARM64_INSN_FCVTZU_SIMD_VECTOR,
    ARM64_INSN_FSQRT_VECTOR,
    ARM64_INSN_BFMLALB_VECTOR,
    ARM64_INSN_BIF_VECTOR,
    ARM64_INSN_MVNI_VECTOR_IMMEDIATE,
    ARM64_INSN_BIC_VECTOR_IMMEDIATE,
    ARM64_INSN_FMULX_VECTOR_BY_ELEMENT,
    ARM64_INSN_USHR_VECTOR_IMMEDIATE,
    ARM64_INSN_FCMLA_VECTOR_BY_ELEMENT,
    ARM64_INSN_SQRDMLAH_VECTOR_BY_ELEMENT,
    ARM64_INSN_SQRDMLSH_VECTOR_BY_ELEMENT,
    ARM64_INSN_FMLAL2_VECTOR_BY_ELEMENT,
    ARM64_INSN_FMLSL2_VECTOR_BY_ELEMENT,
    ARM64_INSN_UDOT_VECTOR_BY_ELEMENT,

    // 0x31...... 立即数数据处理：置标志加法、逻辑或与位域（ADDS、ORR、BFM）。
    ARM64_INSN_ADDS_IMMEDIATE,
    ARM64_INSN_ORR_IMMEDIATE,
    ARM64_INSN_BFM,

    // 0x34...... 分支、异常与系统：比较及测试位分支（CBZ、CBNZ、TBZ）。
    ARM64_INSN_CBZ,
    ARM64_INSN_CBNZ,
    ARM64_INSN_TBZ,
    ARM64_INSN_TBNZ,

    // 0x38...... 加载与存储：GPR 单寄存器、LSE 原子与无符号偏移（STUR、LDADD、LDR）。
    ARM64_INSN_STUR_GPR,
    ARM64_INSN_STR_GPR_POST_INDEX,
    ARM64_INSN_STTR_GPR,
    ARM64_INSN_STR_GPR_PRE_INDEX,
    ARM64_INSN_LDADD,
    ARM64_INSN_LDCLR,
    ARM64_INSN_LDEOR,
    ARM64_INSN_LDSET,
    ARM64_INSN_LDSMAX,
    ARM64_INSN_STR_GPR_REGISTER_OFFSET,
    ARM64_INSN_LDSMIN,
    ARM64_INSN_LDUMAX,
    ARM64_INSN_LDUMIN,
    ARM64_INSN_SWP,
    ARM64_INSN_LDUR_GPR,
    ARM64_INSN_LDR_GPR_POST_INDEX,
    ARM64_INSN_LDTR_GPR,
    ARM64_INSN_LDR_GPR_PRE_INDEX,
    ARM64_INSN_LDADDL,
    ARM64_INSN_LDCLRL,
    ARM64_INSN_LDEORL,
    ARM64_INSN_LDSETL,
    ARM64_INSN_LDSMAXL,
    ARM64_INSN_LDR_GPR_REGISTER_OFFSET,
    ARM64_INSN_LDSMINL,
    ARM64_INSN_LDUMAXL,
    ARM64_INSN_LDUMINL,
    ARM64_INSN_SWPL,
    ARM64_INSN_LDUR_SIGNED_GPR,
    ARM64_INSN_LDR_SIGNED_GPR_POST_INDEX,
    ARM64_INSN_LDTR_SIGNED_GPR,
    ARM64_INSN_LDR_SIGNED_GPR_PRE_INDEX,
    ARM64_INSN_LDADDA,
    ARM64_INSN_LDCLRA,
    ARM64_INSN_LDEORA,
    ARM64_INSN_LDSETA,
    ARM64_INSN_LDSMAXA,
    ARM64_INSN_LDR_SIGNED_GPR_REGISTER_OFFSET,
    ARM64_INSN_LDSMINA,
    ARM64_INSN_LDUMAXA,
    ARM64_INSN_LDUMINA,
    ARM64_INSN_SWPA,
    ARM64_INSN_LDAPR,
    ARM64_INSN_LDADDAL,
    ARM64_INSN_LDCLRAL,
    ARM64_INSN_LDEORAL,
    ARM64_INSN_LDSETAL,
    ARM64_INSN_LDSMAXAL,
    ARM64_INSN_LDSMINAL,
    ARM64_INSN_LDUMAXAL,
    ARM64_INSN_LDUMINAL,
    ARM64_INSN_SWPAL,
    ARM64_INSN_STR_GPR_UNSIGNED_OFFSET,
    ARM64_INSN_LDR_GPR_UNSIGNED_OFFSET,
    ARM64_INSN_LDR_SIGNED_GPR_UNSIGNED_OFFSET,

    // 0x3A...... 寄存器数据处理：带进位置标志与条件比较（ADCS、CCMN register、CCMN immediate）。
    ARM64_INSN_ADCS,
    ARM64_INSN_CCMN_REGISTER,
    ARM64_INSN_CCMN_IMMEDIATE,

    // 0x3C...... 加载与存储：FP/SIMD 单寄存器访存（STUR、STR、LDR）。
    ARM64_INSN_STUR_FP_SIMD,
    ARM64_INSN_STR_FP_SIMD_POST_INDEX,
    ARM64_INSN_STR_FP_SIMD_PRE_INDEX,
    ARM64_INSN_STR_FP_SIMD_REGISTER_OFFSET,
    ARM64_INSN_LDUR_FP_SIMD,
    ARM64_INSN_LDR_FP_SIMD_POST_INDEX,
    ARM64_INSN_LDR_FP_SIMD_PRE_INDEX,
    ARM64_INSN_LDR_FP_SIMD_REGISTER_OFFSET,
    ARM64_INSN_STR_FP_SIMD_UNSIGNED_OFFSET,
    ARM64_INSN_LDR_FP_SIMD_UNSIGNED_OFFSET,

    // 0x4A...... 寄存器数据处理：异或与减法（EOR、EON、SUB）。
    ARM64_INSN_EOR_SHIFTED_REGISTER,
    ARM64_INSN_EON_SHIFTED_REGISTER,
    ARM64_INSN_SUB_SHIFTED_REGISTER,
    ARM64_INSN_SUB_EXTENDED_REGISTER,

    // 0x4E...... SIMD 与浮点数据处理：GPR 插入、窄化与矩阵乘（INS、XTN2、SMMLA）。
    ARM64_INSN_INS_GPR_VECTOR,
    ARM64_INSN_XTN2_VECTOR,
    ARM64_INSN_SQXTN2_VECTOR,
    ARM64_INSN_SMMLA_VECTOR,
    ARM64_INSN_USMMLA_VECTOR,
    ARM64_INSN_BFMLALT_VECTOR_BY_ELEMENT,

    // 0x51...... 立即数数据处理：减法、异或与宽立即数（SUB、EOR、MOVZ）。
    ARM64_INSN_SUB_IMMEDIATE,
    ARM64_INSN_EOR_IMMEDIATE,
    ARM64_INSN_MOVZ,
    ARM64_INSN_UBFM,

    // 0x54...... 分支、异常与系统：条件立即分支（B.cond）。
    ARM64_INSN_B_COND,

    // 0x5A...... 寄存器数据处理：借位减、条件选择与位操作（SBC、CSINV、RBIT）。
    ARM64_INSN_SBC,
    ARM64_INSN_CSINV,
    ARM64_INSN_CSNEG,
    ARM64_INSN_RBIT,
    ARM64_INSN_REV16,
    ARM64_INSN_REV32,
    ARM64_INSN_CLZ,
    ARM64_INSN_CLS,
    ARM64_INSN_CTZ,
    ARM64_INSN_CNT,
    ARM64_INSN_ABS,

    // 0x5E...... SIMD 与浮点数据处理：标量复制、饱和算术与逐元素浮点（DUP、SQADD、FMLA）。
    ARM64_INSN_DUP_ELEMENT_SCALAR,
    ARM64_INSN_SQADD_SCALAR,
    ARM64_INSN_SQSUB_SCALAR,
    ARM64_INSN_SQSHL_SCALAR,
    ARM64_INSN_SQRSHL_SCALAR,
    ARM64_INSN_FMULX_SCALAR,
    ARM64_INSN_FCMEQ_SCALAR,
    ARM64_INSN_FRECPS_SCALAR,
    ARM64_INSN_SQXTN_SCALAR,
    ARM64_INSN_FCVTNS_SIMD_SCALAR,
    ARM64_INSN_FCVTMS_SIMD_SCALAR,
    ARM64_INSN_FCVTAS_SIMD_SCALAR,
    ARM64_INSN_SCVTF_SIMD_SCALAR,
    ARM64_INSN_FADDP_SCALAR_REDUCE,
    ARM64_INSN_SQDMULH_SCALAR,
    ARM64_INSN_FCMGT_ZERO_SCALAR,
    ARM64_INSN_FCMEQ_ZERO_SCALAR,
    ARM64_INSN_FCMLT_ZERO_SCALAR,
    ARM64_INSN_FRSQRTS_SCALAR,
    ARM64_INSN_FCVTPS_SIMD_SCALAR,
    ARM64_INSN_FCVTZS_SIMD_SCALAR,
    ARM64_INSN_CMGT_SCALAR,
    ARM64_INSN_CMGE_SCALAR,
    ARM64_INSN_SSHL_SCALAR,
    ARM64_INSN_SRSHL_SCALAR,
    ARM64_INSN_ADD_SCALAR,
    ARM64_INSN_CMTST_SCALAR,
    ARM64_INSN_FMLA_SCALAR_BY_ELEMENT,
    ARM64_INSN_FMLS_SCALAR_BY_ELEMENT,
    ARM64_INSN_FMUL_SCALAR_BY_ELEMENT,

    // 0x68...... 加载与存储：有符号字成对加载（LDPSW post-index、offset、pre-index）。
    ARM64_INSN_LDPSW_POST_INDEX,
    ARM64_INSN_LDPSW_OFFSET,
    ARM64_INSN_LDPSW_PRE_INDEX,

    // 0x6A...... 寄存器数据处理：置标志逻辑与减法（ANDS、BICS、SUBS）。
    ARM64_INSN_ANDS_SHIFTED_REGISTER,
    ARM64_INSN_BICS_SHIFTED_REGISTER,
    ARM64_INSN_SUBS_SHIFTED_REGISTER,
    ARM64_INSN_SUBS_EXTENDED_REGISTER,

    // 0x6E...... SIMD 与浮点数据处理：元素插入、窄化与矩阵乘（INS、SQXTUN2、BFMMLA）。
    ARM64_INSN_INS_ELEMENT_VECTOR,
    ARM64_INSN_SQXTUN2_VECTOR,
    ARM64_INSN_UQXTN2_VECTOR,
    ARM64_INSN_BFMMLA_VECTOR,
    ARM64_INSN_UMMLA_VECTOR,
    ARM64_INSN_BFMLALT_VECTOR,

    // 0x71...... 立即数数据处理：置标志减法、逻辑与及宽立即数保持（SUBS、ANDS、MOVK）。
    ARM64_INSN_SUBS_IMMEDIATE,
    ARM64_INSN_ANDS_IMMEDIATE,
    ARM64_INSN_MOVK,

    // 0x7A...... 寄存器数据处理：带借位置标志与条件比较（SBCS、CCMP register、CCMP immediate）。
    ARM64_INSN_SBCS,
    ARM64_INSN_CCMP_REGISTER,
    ARM64_INSN_CCMP_IMMEDIATE,

    // 0x7E...... SIMD 与浮点数据处理：无符号标量饱和算术与比较（UQADD、UQSUB、FCMGE）。
    ARM64_INSN_UQADD_SCALAR,
    ARM64_INSN_UQSUB_SCALAR,
    ARM64_INSN_UQSHL_SCALAR,
    ARM64_INSN_UQRSHL_SCALAR,
    ARM64_INSN_FCMGE_SCALAR,
    ARM64_INSN_FACGE_SCALAR,
    ARM64_INSN_SQXTUN_SCALAR,
    ARM64_INSN_UQXTN_SCALAR,
    ARM64_INSN_FCVTNU_SIMD_SCALAR,
    ARM64_INSN_FCVTMU_SIMD_SCALAR,
    ARM64_INSN_FCVTAU_SIMD_SCALAR,
    ARM64_INSN_UCVTF_SIMD_SCALAR,
    ARM64_INSN_SQRDMLAH_SCALAR,
    ARM64_INSN_SQRDMLSH_SCALAR,
    ARM64_INSN_SQRDMULH_SCALAR,
    ARM64_INSN_FCMGE_ZERO_SCALAR,
    ARM64_INSN_FABD_SCALAR,
    ARM64_INSN_FCMLE_ZERO_SCALAR,
    ARM64_INSN_FCMGT_SCALAR,
    ARM64_INSN_FACGT_SCALAR,
    ARM64_INSN_FCVTPU_SIMD_SCALAR,
    ARM64_INSN_FCVTZU_SIMD_SCALAR,
    ARM64_INSN_CMHI_SCALAR,
    ARM64_INSN_CMHS_SCALAR,
    ARM64_INSN_USHL_SCALAR,
    ARM64_INSN_URSHL_SCALAR,
    ARM64_INSN_SUB_SCALAR,
    ARM64_INSN_CMEQ_SCALAR,
    ARM64_INSN_FMULX_SCALAR_BY_ELEMENT,
    ARM64_INSN_SQRDMLAH_SCALAR_BY_ELEMENT,
    ARM64_INSN_SQRDMLSH_SCALAR_BY_ELEMENT,

    // 0x88...... 加载与存储：成对独占访存（STXP、LDXP、LDAXP）。
    ARM64_INSN_STXP,
    ARM64_INSN_STLXP,
    ARM64_INSN_LDXP,
    ARM64_INSN_LDAXP,

    // 0x90...... 立即数数据处理：页相对地址生成（ADRP）。
    ARM64_INSN_ADRP,

    // 0x94...... 分支、异常与系统：带链接无条件分支（BL）。
    ARM64_INSN_BL,

    // 0x98...... 加载与存储：有符号字字面量加载（LDRSW literal）。
    ARM64_INSN_LDRSW_LITERAL,

    // 0x9A...... 寄存器数据处理：64 位 CRC 与长乘法（CRC32X、SMADDL、UMULH）。
    ARM64_INSN_CRC32X,
    ARM64_INSN_CRC32CX,
    ARM64_INSN_SMADDL,
    ARM64_INSN_SMSUBL,
    ARM64_INSN_SMULH,
    ARM64_INSN_UMADDL,
    ARM64_INSN_UMSUBL,
    ARM64_INSN_UMULH,

    // 0x9E...... SIMD 与浮点数据处理：64 位 GPR 到标量浮点转换（SCVTF S,X、SCVTF D,X、UCVTF S,X）。
    ARM64_INSN_SCVTF_S_X,
    ARM64_INSN_UCVTF_S_X,
    ARM64_INSN_SCVTF_D_X,
    ARM64_INSN_UCVTF_D_X,

    // 0xD4...... 分支、异常与系统：异常、提示、屏障及寄存器分支（SVC、NOP、RET）。
    ARM64_INSN_SVC,
    ARM64_INSN_HVC,
    ARM64_INSN_SMC,
    ARM64_INSN_BRK,
    ARM64_INSN_HLT,
    ARM64_INSN_NOP,
    ARM64_INSN_YIELD,
    ARM64_INSN_WFE,
    ARM64_INSN_WFI,
    ARM64_INSN_SEV,
    ARM64_INSN_SEVL,
    ARM64_INSN_PACIASP,
    ARM64_INSN_BTI,
    ARM64_INSN_CLREX,
    ARM64_INSN_DSB,
    ARM64_INSN_DMB,
    ARM64_INSN_ISB,
    ARM64_INSN_MSR_REGISTER,
    ARM64_INSN_MRS,
    ARM64_INSN_BR,
    ARM64_INSN_BLR,
    ARM64_INSN_RET,
    ARM64_INSN_ERET,
    ARM64_INSN_DRPS,

    // 0xD8...... 加载与存储：字面量预取（PRFM literal）。
    ARM64_INSN_PRFM_LITERAL,

    // 0xDA...... 寄存器数据处理：64 位字节反转（REV64）。
    ARM64_INSN_REV64,

    // 0xF8...... 加载与存储：预取寻址形式（PRFUM、PRFM register、PRFM unsigned）。
    ARM64_INSN_PRFUM,
    ARM64_INSN_PRFM_REGISTER_OFFSET,
    ARM64_INSN_PRFM_UNSIGNED_OFFSET,
};

enum arm64_memory_address_mode
{
    ARM64_MEMORY_ADDRESS_NONE,
    ARM64_MEMORY_ADDRESS_LITERAL,
    ARM64_MEMORY_ADDRESS_BASE_OFFSET,
    ARM64_MEMORY_ADDRESS_POST_INDEX,
    ARM64_MEMORY_ADDRESS_PRE_INDEX,
    ARM64_MEMORY_ADDRESS_REGISTER_OFFSET,
};

struct arm64_decoded_insn
{
    // 顶层指令大类，对应 Arm A64 main encoding table；具体编码形式由 instruction 唯一确定。
    enum arm64_insn_class
    {
        ARM64_INSN_CLASS_UNKNOWN, // 无效/尚未分类，不是指令类别

        ARM64_INSN_CLASS_SME, // SME 可伸缩矩阵扩展指令，当前仅识别编码空间
        ARM64_INSN_CLASS_SVE, // SVE 可伸缩向量扩展指令，当前仅识别编码空间
        ARM64_INSN_CLASS_LOAD_STORE,
        ARM64_INSN_CLASS_DATA_PROCESSING_REGISTER,
        ARM64_INSN_CLASS_DATA_PROCESSING_SIMD_FP,
        ARM64_INSN_CLASS_DATA_PROCESSING_IMMEDIATE,
        ARM64_INSN_CLASS_BRANCH_EXCEPTION_SYSTEM,
    } insn_class;

    enum arm64_instruction instruction;

    /*
    以下成员是所有已支持编码形式可能使用的语义字段集合，不是固定数量的操作数槽。
    一条指令通常只填写其中少数字段；ARM64_DECODE_OK 时，由 instruction 决定哪些字段有效。
    */

    // 普通立即数、相对偏移及 DecodeBitMasks 展开结果。
    int64_t offset;              // 已完成符号扩展和尺度换算的相对偏移，单位为字节
    uint64_t immediate;          // 普通立即数；符号扩展和移位规则由 instruction 决定
    uint64_t expanded_immediate; // SIMD modified immediate 展开后的完整位模式
    uint64_t wmask;              // ARM DecodeBitMasks 生成的写掩码
    uint64_t tmask;              // ARM DecodeBitMasks 生成的顶部掩码

    // 访存属性。
    enum arm64_memory_address_mode memory_address_mode; // 有效地址计算和基址写回形式
    uint8_t access_bytes;                               // 单个访存元素的宽度，单位为字节
    uint8_t prefetch_operation;                         // PRFM/PRFUM 的 5 位预取操作编码

    // 寄存器扩展、移位及其他编码修饰。
    uint8_t extend_type;  // 寄存器扩展类型编码
    uint8_t shift_type;   // 移位类型编码
    uint8_t shift_amount; // 移位位数
    uint8_t option;       // 屏障、提示等指令使用的 option 编码
    uint8_t immr;         // 位掩码立即数中的旋转量编码
    uint8_t condition;    // 条件码
    uint8_t nzcv;         // 条件比较失败时写入的 NZCV 值
    uint8_t test_bit;     // TBZ/TBNZ 测试的位编号

    //系统寄存器由 op0、op1、CRn、CRm、op2 打包为 ARM64_SYSREG_KEY。
    uint16_t sysreg;

    // SIMD/FP 元素布局。宽度单位均为位，索引从 0 开始。
    uint8_t element_width;
    uint8_t lane_index;
    uint8_t source_lane_index;

    /*
    A64 编码图中的寄存器指定字段，均保存 5 位编号。
    它们不是固定的“第几个汇编操作数”；寄存器组及编号 31 的含义由 instruction 决定。
    */
    uint8_t rd;  // Rd 字段
    uint8_t rn;  // Rn 字段
    uint8_t rm;  // Rm 字段
    uint8_t ra;  // Ra 字段
    uint8_t rt;  // Rt 字段
    uint8_t rt2; // Rt2 字段
    uint8_t rs;  // Rs 字段

    /* 主操作数位宽或有效向量位宽，单位为位。 */
    uint8_t operand_width;
};

/*
解码一条 AArch64 指令。

调用方提供最终结果存储地址，decoder 直接填充该对象，避免大结构体按值返回时
产生隐藏返回槽以及调用端的结构体复制。

返回值为 OK 时，instruction 和该指令对应的 operands 完整有效。
返回值为 UNSUPPORTED 时，只保证 insn_class；调用方不得依赖 instruction 或 operands 执行或重定位。
返回值为 UNPREDICTABLE 或 UNALLOCATED 时，不保证输出结构中的字段有效。
参数0:待解码的一条 32 位 A64 指令机器码
参数1:解码结果
*/
enum arm64_decode_status arm64_decode_insn(uint32_t raw, struct arm64_decoded_insn *decoded);

#endif
